// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm_oW5TtWKIEfuRVfodZ_gte4LqANTkrQ',
    appId: '1:313848050108:web:79bb87c186b045cfc93bb9',
    messagingSenderId: '313848050108',
    projectId: 'news-app-b0f5e',
    authDomain: 'news-app-b0f5e.firebaseapp.com',
    storageBucket: 'news-app-b0f5e.firebasestorage.app',
    measurementId: 'G-81N86MPX5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPORV7qkxCf_tQDdGps4LeerHUiUF6x6k',
    appId: '1:313848050108:android:4d25510cd16f737ac93bb9',
    messagingSenderId: '313848050108',
    projectId: 'news-app-b0f5e',
    storageBucket: 'news-app-b0f5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCckao86Shhm5qCJtobbxgRK2veVXtttbY',
    appId: '1:313848050108:ios:a3c88027d569cf3ec93bb9',
    messagingSenderId: '313848050108',
    projectId: 'news-app-b0f5e',
    storageBucket: 'news-app-b0f5e.firebasestorage.app',
    iosClientId: '313848050108-cs1m8v3d65ikot2ecamqano5j2gl235n.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );

}