name: Flutter Continuous Integration (CI)

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, Analyze & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create .env File
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: |
          echo "NEWS_API_KEY=$NEWS_API_KEY" > .env

      - name: Create Firebase Options
        env:
          FIREBASE_OPTIONS_BASE64: ${{ secrets.FIREBASE_OPTIONS_BASE64 }}
        run: |
          echo "$FIREBASE_OPTIONS_BASE64" | base64 --decode > lib/firebase_options.dart

      - name: Create google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo "$GOOGLE_SERVICES_JSON" | base64 --decode > android/app/google-services.json

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Cache Flutter Packages
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze Code
        run: flutter analyze

      - name: Build Release APK
        run: flutter build apk --release --android-skip-build-dependency-validation

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: news-app-apk
          path: build/app/outputs/flutter-apk/app-release.apk